4_Fornecedor/Sprint3/Fornecedor/fornecedor/urls.py
from django.urls import path

from . import views

app_name = 'fornecedor'
urlpatterns = [
    path('listar/', views.ProviderListView.as_view(), name='listar'),
    path('criar/', views.ProviderCreateView.as_view(), name='criar'),
    path('<int:pk>/editar', views.ProviderUpdateView.as_view(), name='editar'),
    path('<int:pk>/deletar', views.ProviderDeleteView.as_view(), name='deletar'),

    path('listar_representante/', views.RepresentativeListView.as_view(), name='listar_representante'),
    path('criar_representante/', views.RepresentativeCreateView.as_view(), name='criar_representante'),
    path('<int:pk>/editar_representante', views.RepresentativeUpdateView.as_view(), name='editar_representante'),
    path('<int:pk>/deletar_representante', views.RepresentativeDeleteView.as_view(), name='deletar_representante'),

    path('listar_produto/', views.ProductListView.as_view(), name='listar_produto'),
    path('criar_produto/', views.ProductCreateView.as_view(), name='criar_produto'),
    path('<int:pk>/editar_produto', views.ProductUpdateView.as_view(), name='editar_produto'),
    path('<int:pk>/deletar_produto', views.ProductDeleteView.as_view(), name='deletar_produto'),

    path('listar_estoque/', views.StockListView.as_view(), name='listar_estoque'),
    path('criar_estoque/', views.StockCreateView.as_view(), name='criar_estoque'),
    path('<int:pk>/editar_estoque', views.StockUpdateView.as_view(), name='editar_estoque'),

    path('pedido/', views.OrderListView.as_view(), name='pedido'),
    path('venda/', views.SellListView.as_view(), name='venda'),




]

4_Fornecedor/Sprint3/Fornecedor/stepesbd/urls.py
from django.contrib import admin
from django.urls import path, include
from stepesbd.views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluindo as urls do fornecedor.urls e colocando no fornecedor/.
    path('fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    #path('representante/', include('representante.urls', namespace='representante')),
    #path('produto/', include('produto.urls', namespace='produto')),
    #path('estoque/', include('estoque.urls', namespace='estoque')),
    path('', index, name='index')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4_Fornecedor/Sprint3/Fornecedor/templates/base.html
<!-- carregando os staticfiles -->
{% load staticfiles %}

<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="description" content="A high-quality &amp; free Bootstrap admin dashboard template pack that comes with lots of templates and components.">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://use.fontawesome.com/releases/v5.0.6/css/all.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" id="main-stylesheet" data-version="1.1.0" href="styles/shards-dashboards.1.1.0.min.css">
    <link rel="stylesheet" href="styles/extras.1.1.0.min.css">
    <script async defer src="https://buttons.github.io/buttons.js"></script>
    <title>Stepes-BD - {% block title %}Home{% endblock %}</title>
  </head>
  <body>
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Time 4</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
          <ul class="nav navbar-nav">
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Fornecedor <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'fornecedor:listar' %}">Listar</a></li>
                <li><a href="{% url 'fornecedor:criar' %}">Novo</a></li>
              </ul>
            </li>

             <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Representante <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'fornecedor:listar_representante' %}">Listar</a></li>
                <li><a href="{% url 'fornecedor:criar_representante' %}">Novo</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Produto <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'fornecedor:listar_produto' %}">Listar</a></li>
                <li><a href="{% url 'fornecedor:criar_produto' %}">Novo</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Estoque <span class="caret"></span></a>
              <ul class="dropdown-menu">
                <li><a href="{% url 'fornecedor:listar_estoque' %}">Listar</a></li>
                <li><a href="{% url 'fornecedor:criar_estoque' %}">Novo</a></li>
              </ul>
            </li>

            <li class="dropdown">
              <a href="{% url 'fornecedor:pedido' %}" class="dropdown-toggle" role="button">Entrada de Pedido </a>
            </li>

            <li class="dropdown">
              <a href="{% url 'fornecedor:venda' %}" class="dropdown-toggle"  role="button" >Venda<span </a>
            </li>

          </ul>
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>
    <div class="container-fluid">
      {% block content %}
      {% endblock %}
    </div>
  </body>
  <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.10.1/jquery.min.js"></script>

  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</html>

4_Fornecedor/Sprint3/Fornecedor/templates/index.html
{% extends 'base.html' %}

{% block title %} Home{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
      <h1>STEPES-BD</h1>
    </div>
  </div>
{% endblock %}