4_Fornecedor/Sprint3/Fornecedor/fornecedor/urls.py
from django.urls import path

from . import views

app_name = 'fornecedor'
urlpatterns = [
    path('listar/', views.ProviderListView.as_view(), name='listar'),
    path('criar/', views.ProviderCreateView.as_view(), name='criar'),
    path('<int:pk>/editar', views.ProviderUpdateView.as_view(), name='editar'),
    path('<int:pk>/deletar', views.ProviderDeleteView.as_view(), name='deletar'),

    path('listar_representante/', views.RepresentativeListView.as_view(), name='listar_representante'),
    path('criar_representante/', views.RepresentativeCreateView.as_view(), name='criar_representante'),
    path('<int:pk>/editar_representante', views.RepresentativeUpdateView.as_view(), name='editar_representante'),
    path('<int:pk>/deletar_representante', views.RepresentativeDeleteView.as_view(), name='deletar_representante'),

    path('listar_produto/', views.ProductListView.as_view(), name='listar_produto'),
    path('criar_produto/', views.ProductCreateView.as_view(), name='criar_produto'),
    path('<int:pk>/editar_produto', views.ProductUpdateView.as_view(), name='editar_produto'),
    path('<int:pk>/deletar_produto', views.ProductDeleteView.as_view(), name='deletar_produto'),

    path('listar_estoque/', views.StockListView.as_view(), name='listar_estoque'),
    path('criar_estoque/', views.StockCreateView.as_view(), name='criar_estoque'),
    path('<int:pk>/editar_estoque', views.StockUpdateView.as_view(), name='editar_estoque'),

    path('pedido/', views.OrderListView.as_view(), name='pedido'),
    path('venda/', views.SellListView.as_view(), name='venda'),




]

4_Fornecedor/Sprint3/Fornecedor/stepesbd/urls.py
from django.contrib import admin
from django.urls import path, include
from stepesbd.views import index
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # Incluindo as urls do fornecedor.urls e colocando no fornecedor/.
    path('fornecedor/', include('fornecedor.urls', namespace='fornecedor')),
    #path('representante/', include('representante.urls', namespace='representante')),
    #path('produto/', include('produto.urls', namespace='produto')),
    #path('estoque/', include('estoque.urls', namespace='estoque')),
    path('', index, name='index')
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

4_Fornecedor/Sprint3/Fornecedor/fornecedor/models.py
from django.db import models
from django.core.validators import MaxValueValidator
from fornecedor.helper_functions import *


class Provider(models.Model):
    PRO_ID = models.AutoField(primary_key=True)
    PRO_CNPJ = models.CharField('Cnpj',unique=True, max_length=14, validators=[validate_CNPJ])
    PRO_SOCIAL_REASON = models.CharField('Razão social',max_length=45,null=False)
    PRO_ADRESS = models.CharField('Endereço',max_length=45,null=False)
    PRO_CONTACT = models.DecimalField('Contato',null=False,max_digits=11, decimal_places=0)

    # Função responsavel por pela label do objeto numa lista
    def __str__(self):
        return self.PRO_SOCIAL_REASON

class Representative(models.Model):
    REP_ID = models.AutoField(primary_key=True)
    REP_CPF = models.CharField('Cpf',unique=True, max_length=14, validators=[validate_CPF])
    REP_NAME = models.CharField('Nome',max_length=45,null=False)
    REP_CONTACT = models.DecimalField('Telefone Fixo',null=False,max_digits=10, decimal_places=0)
    REP_CONTACT_CEL = models.DecimalField('Celular',null=False,max_digits=11, decimal_places=0)
    REP_CONTACT_EMAIL = models.CharField('Email', max_length=45,null=True)
    REP_PROVIDER = models.ForeignKey(Provider,verbose_name='Fornecedor', on_delete=models.CASCADE)

    def __str__(self):
        return self.REP_NAME

class Contact(models.Model):
    CON_ID = models.AutoField(primary_key=True)
    CON_CONTACT_TYPE = models.CharField(max_length=45,null=False)
    CON_CONTACT_DESCRIPTION = models.CharField(max_length=45,null=False)
    CON_CPF_REPRESENTATIVE = models.ForeignKey(Representative, on_delete=models.CASCADE)

class Product(models.Model):
    PRD_ID = models.AutoField(primary_key=True)
    PRD_NAME = models.CharField('Nome do produto',max_length=45,null=False)
    PRD_DESCRIPTION = models.CharField('Descrição',max_length=45,null=False)
    PRD_PROVIDER = models.ForeignKey(Provider,verbose_name='Fornecedor',on_delete=models.CASCADE)
    #PRD_IMAGE = models.ImageField(upload_to='imagens/', null=True, blank=True)
    def __str__(self):
        return self.PRD_DESCRIPTION

class Stock(models.Model):
    STK_ID =  models.AutoField(primary_key=True)
    STK_TYPE =  models.CharField(verbose_name='Tipo',max_length=45,blank=False, null=False)
    STK_PRODUCT = models.ForeignKey(Product, verbose_name='Produto',on_delete=models.CASCADE)
    STK_QUANTITY = models.PositiveIntegerField('Quantidade',null=False)

    def __str__(self):
        return self.STK_PRODUCT

class Order(models.Model):
    ord_id = models.AutoField(primary_key=True)
    ord_asset_id = models.CharField(max_length=255)
    ord_date = models.DateField(blank=True, null=True)
    ord_quantity = models.IntegerField()
    ord_status = models.CharField(max_length=50, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'Order'
        app_label = 'hospital'

4_Fornecedor/Sprint3/Fornecedor/fornecedor/views.py
from django.urls import reverse_lazy
from fornecedor.models import Provider,Representative,Product,Stock, Order
from django.views.generic.edit import UpdateView, CreateView, DeleteView, View
from django.views import generic
from django.db.models import F
from django.shortcuts import render_to_response

# Lista Provider

class ProviderListView(generic.ListView):
    model = Provider
    template_name = 'fornecedor_listar.html'
    context_object_name = 'fornecedores'
    paginate_by = 5


class ProviderUpdateView(UpdateView):
    model = Provider
    template_name = 'fornecedor_editar.html'
    fields = '__all__'
    context_object_name = 'fornecedor'
    success_url = reverse_lazy('fornecedor:listar')


class ProviderCreateView(CreateView):
    model = Provider
    template_name = 'fornecedor_criar.html'
    fields = '__all__'
    success_url = reverse_lazy('fornecedor:listar')


class ProviderDeleteView(DeleteView):
    model = Provider
    context_object_name = 'fornecedor'
    template_name = 'fornecedor_confirmacao_deletar.html'
    success_url = reverse_lazy('fornecedor:listar')

###########################################################################################
class RepresentativeListView(generic.ListView):
    model = Representative
    template_name = 'representante_listar.html'
    context_object_name = 'representantes'
    paginate_by = 5


class RepresentativeUpdateView(UpdateView):
    model = Representative
    template_name = 'representante_editar.html'
    fields = '__all__'
    context_object_name = 'representante'
    success_url = reverse_lazy('fornecedor:listar_representante')


class RepresentativeCreateView(CreateView):
    model = Representative
    template_name = 'representante_criar.html'
    fields = '__all__'
    success_url = reverse_lazy('fornecedor:listar_representante')


class RepresentativeDeleteView(DeleteView):
    model = Representative
    context_object_name = 'representante'
    template_name = 'representante_confirmacao_deletar.html'
    success_url = reverse_lazy('fornecedor:listar_representante')
###########################################################################################
class ProductListView(generic.ListView):
    model = Product
    template_name = 'produto_listar.html'
    context_object_name = 'produtos'
    paginate_by = 5


class ProductUpdateView(UpdateView):
    model = Product
    template_name = 'produto_editar.html'
    fields = '__all__'
    context_object_name = 'produto'
    success_url = reverse_lazy('fornecedor:listar_produto')


class ProductCreateView(CreateView):
    model = Product
    template_name = 'produto_criar.html'
    fields = '__all__'
    success_url = reverse_lazy('fornecedor:listar_produto')


class ProductDeleteView(DeleteView):
    model = Product
    context_object_name = 'produto'
    template_name = 'produto_confirmacao_deletar.html'
    success_url = reverse_lazy('fornecedor:listar_produto')
###########################################################################################
class StockListView(generic.ListView):
    model = Stock
    template_name = 'estoque_listar.html'
    context_object_name = 'estoques'
    paginate_by = 5

class StockCreateView(CreateView):
    model = Stock
    template_name = 'estoque_criar.html'
    fields = '__all__'
    success_url = reverse_lazy('fornecedor:listar_estoque')

class StockUpdateView(UpdateView):
    model = Stock
    template_name = 'estoque_editar.html'
    fields = '__all__'
    context_object_name = 'estoque'
    success_url = reverse_lazy('fornecedor:listar_estoque')
    paginate_by = 5
 ###########################################################################################

class OrderListView(generic.ListView):
    model = Order
    template_name = 'pedido.html'
    context_object_name = 'pedidos'
    paginate_by = 5

class OrderUpdateView(UpdateView):
    model = Stock
    template_name = 'venda.html'
    fields = '__all__'
    context_object_name = 'pedidos'
    success_url = reverse_lazy('fornecedor:venda')
    paginate_by = 5

class SellListView(generic.ListView):
    model = Order
    template_name = 'venda.html'
    context_object_name = 'vendas'
    paginate_by = 5


#def RequestListView(request):
#   return render_to_response('pedido.html')

#def SellListView(request):
#   return render_to_response('venda.html')

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/estoque_confirmacao_deletar.html
{% extends 'base.html' %}

{% block title %} Estoque - Deletar{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Estoque - Deletar estoque {{ estoque.descricao }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          <p>Você tem certeza que quer deletar o estoque de: "{{ estoque.descricao }}"?</p>
          <input type="submit" value="Confirmar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/estoque_criar.html
{% extends 'base.html' %}

{% block title %} Estoque - Novo{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Estoque - Novo estoque</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Salvar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/estoque_listar.html
{% extends 'base.html' %}

{% block title %} Estoque - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Lista de Produtos no estoque: </h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'fornecedor:criar_estoque' %}" class="btn btn-default" role="button">Novo</a>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>Tipo do Produto</td>
        <td>Produto</td>
        <td>Quantidade</td>
        <td>Ações</td>
      </thead>
      <tbody>
        {% for estoque in estoques %}
          <tr>
            <td>
              {{ estoque.STK_TYPE }}
            </td>
            <td>
              {{ estoque.STK_PRODUCT }}
            </td>
            <td>
              {{ estoque.STK_QUANTITY }}
            </td>

            <td>
              <a href="{% url 'fornecedor:editar_estoque' pk=estoque.STK_ID %}">Editar</a>

            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/fornecedor_confirmacao_deletar.html
{% extends 'base.html' %}

{% block title %} Fornecedor - Deletar{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Fornecedor - Deletar fornecedor {{ fornecedor.PRO_SOCIAL_REASON }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          <p>Você tem certeza que quer deletar o usuario com cnpj: "{{ fornecedor.PRO_CNPJ }}"?</p>
          <input type="submit" value="Confirmar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/fornecedor_listar.html
{% extends 'base.html' %}

{% block title %} Fornecedores - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Lista de Fornecedores: </h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'fornecedor:criar' %}" class="btn btn-default" role="button">Novo</a>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>Razão Social</td>
        <td>CNPJ</td>
        <td>Ações</td>
      </thead>
      <tbody>
        {% for fornecedor in fornecedores %}
          <tr>
            <td>
              {{ fornecedor.PRO_SOCIAL_REASON }}
            </td>
            <td>
              {{ fornecedor.PRO_CNPJ }}
            </td>
            <td>
              <a href="{% url 'fornecedor:editar' pk=fornecedor.PRO_ID %}">Editar</a>
              <a href="{% url 'fornecedor:deletar' pk=fornecedor.PRO_ID %}">Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>




{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/pedido.html
{% extends 'base.html' %}

{% block title %} Fornecedores - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Entrada de Pedido </h1>
    </div>
    <div class="col-md-4">
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>ID do Pedido</td>
        <td>Quantidade</td>
        <td>Status</td>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
          <tr>
            <td>
              {{ pedido.ord_id }}
            </td>
            <td>
              {{ pedido.ord_quantity }}
            </td>
            <td>
              {{ pedido.ord_status }}
            </td>
            <td>
              <td><a href="{% url 'fornecedor:venda' %}"class="btn btn-default" role="button">Abrir</a>
            </td>

            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>




{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/produto_criar.html
{% extends 'base.html' %}

{% block title %} Produtos - Novo{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Produto - Novo produto</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Salvar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/produto_editar.html
{% extends 'base.html' %}

{% block title %} Produtos - Editar{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Produto - Editar produto {{ produto.PRD_DESCRIPTION }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Salvar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/produto_listar.html
{% extends 'base.html' %}

{% block title %} Produto - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Lista de Produtos: </h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'fornecedor:criar_produto' %}" class="btn btn-default" role="button">Novo</a>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>Descrição</td>
        <td>Fornecedor</td>
        <td>Imagem</td>
        <td>Ações</td>
      </thead>
      <tbody>
        {% for produto in produtos %}
          <tr>
            <td>
              {{ produto.PRD_NAME }}
            </td>
            <td>
              {{ produto.PRD_DESCRIPTION }}
            </td>
            <td>
              {{ produto.PRD_PROVIDER }}
            </td>

            <td>
              <a href="{% url 'fornecedor:editar_produto' pk=produto.PRD_ID %}">Editar</a>
              <a href="{% url 'fornecedor:deletar_produto' pk=produto.PRD_ID %}">Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>




{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/representante_confirmacao_deletar.html
{% extends 'base.html' %}

{% block title %} Representante - Deletar{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Representante - Deletar representante {{ representante.REP_NAME }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          <p>Você tem certeza que quer deletar o representante com o nome: "{{ representante.REP_NAME }}"?</p>
          <input type="submit" value="Confirmar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/representante_criar.html
{% extends 'base.html' %}

{% block title %} Representante - Novo{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Representante - Novo Representante</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Salvar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/representante_editar.html
{% extends 'base.html' %}

{% block title %} Representantes - Editar{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-12">
        <h1>Representante - Editar Representante {{ representante.REP_NAME }}</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-md-12">
      <form method="post">{% csrf_token %}
          {{ form.as_p }}
          <input type="submit" value="Salvar" />
      </form>
    </div>
  </div>
{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/representante_listar.html
{% extends 'base.html' %}

{% block title %} Representantes - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Lista de Representantes: </h1>
    </div>
    <div class="col-md-4">
      <a href="{% url 'fornecedor:criar_representante' %}" class="btn btn-default" role="button">Novo</a>
    </div>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>Nome</td>
        <td>Fornecedor</td>
        <td>Ações</td>
      </thead>
      <tbody>
        {% for representante in representantes %}
          <tr>
            <td>
              {{ representante.REP_NAME }}
            </td>
            <td>
              {{ representante.REP_PROVIDER }}
            </td>
            <td>
              <a href="{% url 'fornecedor:editar_representante' pk=representante.REP_ID %}">Editar</a>
              <a href="{% url 'fornecedor:deletar_representante' pk=representante.REP_ID %}">Excluir</a>
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>


{% endblock %}

4_Fornecedor/Sprint3/Fornecedor/fornecedor/templates/venda.html
{% extends 'base.html' %}

{% block title %} Fornecedores - Lista{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-md-8">
      <h1>Solicitação de Compra </h1>
    </div>
    <div class="col-md-4">
    </div>
  </div>


<div class="row2">
    <table class="table">
      <thead>
        <td>Número do pedido</td>
        <td>Cnpj Solicitante</td>
        <td>Razão Social</td>
        <td>Responsável</td>
      </thead>
      <tbody>
      <tr>

      </tr>
      </tbody>
    </table>
  </div>
  <div class="row">
    <table class="table">
      <thead>
        <td>Código do Item</td>
        <td>Item</td>
        <td>Especificações</td>
        <td>Número de série</td>
        <td>Lote</td>
        <td>Quantidade</td>
        <td>Preço Unitário</td>
        <td>Preço Total</td>
      </thead>
      <tbody>
        {% for pedido in pedidos %}
          <tr>
            <td>
              {{ pedido.ord_id }}
            </td>
            <td>
              {{ pedido.ord_quantity }}
            </td>
            <td>
              {{ pedido.ord_id }}
            </td>
            <td>
              {{ pedido.ord_quantity }}
            </td>
            <td>
              {{ pedido.ord_id }}
            </td>
            <td>
              {{ pedido.ord_quantity }}
            </td>
            <td>
              {{ pedido.ord_id }}
            </td>
            <td>
              {{ pedido.ord_quantity }}
            </td>

          </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>





{% endblock %}